#!/bin/bash
# POPCLIP_OPTION_APIKEY=""
# POPCLIP_OPTION_PROXY="socks5://127.0.0.1:7890"
# POPCLIP_OPTION_PROMPT1="Please translate to zh-CN"
# POPCLIP_TEXT=""
# POPCLIP_OPTION_MODEL="gpt-3.5-turbo"
# POPCLIP_OPTION_SHOW=1
if [[ $(uname -m) == 'arm64' ]]
then
./openai-cmd-arm64 -k="$POPCLIP_OPTION_APIKEY" -u="$POPCLIP_OPTION_PROXY"  -p="$POPCLIP_OPTION_PROMPT1" -c="$POPCLIP_TEXT" -m="$POPCLIP_OPTION_MODEL" -s=$POPCLIP_OPTION_SHOW
else
./openai-cmd -k="$POPCLIP_OPTION_APIKEY" -u="$POPCLIP_OPTION_PROXY"  -p="$POPCLIP_OPTION_PROMPT1" -c="$POPCLIP_TEXT" -m="$POPCLIP_OPTION_MODEL" -s=$POPCLIP_OPTION_SHOW
fi